### ISSUE TITLE
Clean up error calcs and stdout

### ISSUE THREAD

**Issue by shigh** [shigh/pswr-charm#14]
Do a max reduce on the errors after each iteration instead of each chare printing its own result, then print from the main chare.

Handle the "done at" print out in the main chare.

**Comment by jdsteve2** [comment]
We're talking about the variable "err" right?

**Comment by shigh** [comment]
Yes

**Comment by jdsteve2** [comment]
Done. Wasn't sure what all to print out in done(). Won't be offended if anybody changes it.
