### ISSUE TITLE
Many time chunks

### ISSUE THREAD

**Issue by shigh** [shigh/pswr-charm#15]
Apply SWR many times to different chunks of time. This is so we can solve for long time windows with many nt.
In other words: solve from [0,T], then from [T,2T], ...

This should not be too hard. You will need to add a set_x0 function to region.

**Comment by pranjalv123** [comment]
I'm not totally sure what's involved here... is it just a matter of running the algorithm multiple times, setting the initial conditions for the i^th run based on the result of the (i-1)^th iteration? Or are the [0, T] iterations supposed to go in parallel with the [T, 2T] iterations?

**Comment by pranjalv123** [comment]
never mind I think I got it

**Comment by shigh** [comment]
The first guess was exactly right. This is how you would solve a real problem, and should be easy to fold on what we have.

**Comment by shigh** [comment]
@pranjalv123 , any progress? I would like to have this done in time for the presentation.

**Comment by pranjalv123** [comment]
Yea, ran into some snags. Should be ready soon.

On December 7, 2014 7:52:12 PM CST, shigh notifications@github.com wrote:

> @pranjalv123 , any progress? I would like to have this done in time for
> the presentation.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/shigh/pswr-charm/issues/15#issuecomment-65967171

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shigh** [comment]
I reverted these commits. They are saved in the many-iter branch. Lets go over it tonight, I am not sure what you were doing. 

I think I should not have been saying chunks, sorry. I am being confusing.
