### ISSUE TITLE
keeps running after last iteration?

### ISSUE THREAD

**Issue by pranjalv123** [shigh/pswr-charm#17]
I run something like
./charmrun +p4 ./swr 3 2 10 1  ++mpiexec

and the output is like

Iteration 0: 0.774584
Iteration 1: 0.718327
Iteration 2: 0.323310
Iteration 3: 0.109807
Iteration 4: 0.027737
Iteration 5: 0.009761
Iteration 6: 0.006966
Iteration 7: 0.007393
Iteration 8: 0.006966
Iteration 9: 0.007393
Done at iteration 9 - Error: 0.007393
Iteration 10: 1.565726
Iteration 11: 1.257643
...

and then it crashes around iteration 15

am I doing something wrong or is this a bug?

**Comment by pranjalv123** [comment]
just kidding this is my fault

**Comment by jdsteve2** [comment]
I blieve I've seen this happen since you fixed it... If I catch it again I'll let you know.

**Comment by shigh** [comment]
This has happened to me when you do not specify a load balancer.

**Comment by jdsteve2** [comment]
Just got this with GreedyCommLB running locally on taub:
[0] GreedyCommLB created
Iteration 0: 0.774584
Iteration 1: 0.718327
Iteration 2: 0.323310
Iteration 3: 0.109807
Iteration 4: 0.027737

CharmLB> GreedyCommLB: PE [0] step 0 starting at 11.165417 Memory: 122.332031 MB
CharmLB> GreedyCommLB: PE [0] strategy starting at 11.165715
In GreedyCommLB strategy
CharmLB> Obj Map:
3 2 1 0 0 0 2 1 3 
CharmLB> GreedyCommLB: PE [0] Memory: LBManager: 920 KB CentralLB: 3 KB
CharmLB> GreedyCommLB: PE [0] #Objects migrating: 8, LBMigrateMsg size: 0.00 MB
CharmLB> GreedyCommLB: PE [0] strategy finished at 11.165900 duration 0.000185 s
[0] Starting ReceiveMigration step 0 at 11.166134
CharmLB> GreedyCommLB: PE [0] step 0 finished at 13.683970 duration 2.518553 s

Iteration 5: 0.009761
Iteration 6: 0.006966
Iteration 7: 0.007393
Iteration 8: 0.006966
Done at iteration 9 - Error: 0.006966
Iteration 9: 0.007393

**Comment by pranjalv123** [comment]
no, I think that's fine, it's just the order of the prints that's getting reversed. You'd want Iteration 9:... to be printed, and the fact that it gets printed after the done message is due to non-deterministic ordering of messages in charm++.
