### ISSUE TITLE
Taub tests

### ISSUE THREAD

**Issue by shigh** [shigh/pswr-charm#2]

**Comment by shigh** [comment]
I added a run script to the taub branch. I have a test job in the queue, but it is taking forever to schedule.

See #10 for notes on how I compiled.

**Comment by shigh** [comment]
@pranjalv123 , the job I submitted crashed and burned, but it is a start...

**Comment by shigh** [comment]
@jdsteve2 , Can you spend some time trying to figure this out?

**Comment by jdsteve2** [comment]
I will try to make time to do so, but my track record for getting things to run on taub is pretty terrible. 

By the way guys I'm really sorry I haven't been able to devote more time to this project. I was planning to spend all day on it today. I'm having to pick up more slack in another project where I ended up donig the majority of the work. If I had even the slightest chance of having any time over the next week I would have assigned more of these issues/bugs to myself.

**Comment by shigh** [comment]
I keep getting:

```
        /lib64/ld-linux-x86-64.so.2 (0x00007f57bed0a000)
/home/shigh2/work/pswr-charm/taub/../code/swr: error while loading shared libraries: libpetsc.so.3.5: cannot open shared object file: No such file or directory
/home/shigh2/work/pswr-charm/taub/../code/swr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/shigh2/work/pswr-charm/taub/../code/swr)
```

Petsc is in the path, I double checked with a simple test program. I have no idea what is causing the other error. I hate taub.

**Comment by shigh** [comment]
I just got the exact same errors on MSUs system, so it must be us, not just taub.

I fixed the libstdc++ error by removing all c++11 code, but the petsc link is still giving my problems. I printed the LD_LIBRARY_PATH from each process, and it includes the petsc lib dir. I am completely stumped, any thoughts?

I also tried compiling it with a petsc static library, and that just caused all sorts of hell...

It get better. If you submit the job with ++local it works. If you submit the normal way it crashes.

**Comment by shigh** [comment]
The trick was to remove all c++11 and run with ++mpiexec. I believe it is working now, but we will need to do some scaling studies to make sure that we are actually running in parallel. I did a quick one (going from 8-16 cores) and it came out about right.
