### ISSUE TITLE
Efficient set_dt in heat solver

### ISSUE THREAD

**Issue by shigh** [shigh/pswr-charm#3]
Right now we are rebuilding the entire sparse matrix.

**Comment by jdsteve2** [comment]
I made this more efficient. It now only updates the parts of A that need to change. It probably could still be faster. If someone has a faster method to suggest, make it a new issue.

**Comment by shigh** [comment]
It looks like you left a debug print statement in. I removed it. 

I am sure this is fast enough for now. We have more important issues to tackle.
