### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by shigh** [shigh/pswr-charm#7]

**Comment by shigh** [comment]
@jdsteve2 , You can start running some benchmarks now. If you could get some projections traces by tomorrow that would be great.

**Comment by shigh** [comment]
@jdsteve2 , I just merged everything for benchmarks into master, and send you an email with init results. I think we may have enough for the presentation already...

**Comment by shigh** [comment]
@jdsteve2 , can you get some more results with a few different load balancers tonight? The problem setup currently in master is good enough for now. I might try something more complicated tomorrow if I have time.

Can you also make some figures from the projections results and save them for our presentation.

**Comment by jdsteve2** [comment]
@shigh, which projections graph(s) do you want figures of for each balancer? Just the time profile?

**Comment by shigh** [comment]
Whatever makes us look best. Time profile is a good start.

**Comment by jdsteve2** [comment]
In progress...

**Comment by jdsteve2** [comment]
I have 4 different charts for each of 4 different load balancers, plus DummyLB.

**Comment by jdsteve2** [comment]
Load balancing figures are in pswr-presentations/CS598/figures/LoadBalancing:
https://github.com/shigh/pswr-presentations/tree/master/CS598/figures/LoadBalancing

**Comment by jdsteve2** [comment]
I have added four slides on this to scott_siam14.tex
