### ISSUE TITLE
Load Balancer

### ISSUE THREAD

**Issue by shigh** [shigh/pswr-charm#8]
Load imbalance is the key argument for using Charm++ with this project. We need to have the load balancers working to get any meaningful results.

This will probably require:
- Pup methods in region, solver and SWRDomain.
- Load balancing calls in the charm code

The datastructures are not likely to change by V0.1, so you can start working on this now.

**Comment by pranjalv123** [comment]
@shigh @jdsteve2 does anyone know how to serialize sparse petsc matrices? It's not clear to me from the documentation. Otherwise I'll just rebuild them on the new processor.

**Comment by shigh** [comment]
I would just rebuild it for now. We are already rebuilding each time dt changes...

**Comment by pranjalv123** [comment]
@shigh @jdsteve this is working now (on branch pupping) but there's some problem with Petsc initialization (it crashes when we try to call PetscFinalize() on a migrated chare). Have either of you figured out how to initialize/finalize that the right way? Can we just... not finalize Petsc?

**Comment by shigh** [comment]
I am okay with that... If it causes problems lets try moving it to a node group.

**Comment by shigh** [comment]
If it works with just ignoring PetscFinalize, lets stick with that for now. It makes me nervous though, we should eventually do this the right way. I added issue #11 for this.

**Comment by shigh** [comment]
Why don't we use initnode methods?
http://charm.cs.illinois.edu/manuals/html/charm++/9.html

**Comment by shigh** [comment]
I just tested it with initnode, and it works!
Sorry, I accidently pushed it to master...

**Comment by shigh** [comment]
@pranjalv123 , ~~I meged #11 (via master) into pupping.~~ (It looks like you merged into master at about the same time) 'make test-swr' works, but 'make test' fails with a weird undefined reference to vtable error. See #13.

Update: This is fixed. I changed the structure of the Makefiles and added ifdefs to remove charm code when compliling with g++.

**Comment by pranjalv123** [comment]
ok I re-merged my pupping code with master and added the ifdefs... now I'm going to stop breaking master

**Comment by shigh** [comment]
I had to remove one of you ckmigratemsg constructor overloads in solver.hpp.
I choose the one that calls PUP::able(msg), I'm not sure if that is the correct one.

Why did you add no argument constructors?

**Comment by pranjalv123** [comment]
we need a no argument constructor to construct an object of the appropriate subclass in the pup method (I think).

**Comment by pranjalv123** [comment]
working in commit a04b4b69613e172d953e832fda6103ba876b7032
