### ISSUE TITLE
What benchmarks do we need? Please list here.

### ISSUE THREAD

**Issue by jdsteve2** [shigh/pswr-charm#9]
(run configuration, desired output data)

**Comment by pranjalv123** [comment]
We want to find the relationship between level of decomposition and load
imbalance - that is, how loaded is the most loaded processor across
different granularities?

**Comment by shigh** [comment]
I think something along these lines would be a great example:
Intialize half of the domains with mesh spacing dx, the other half with dx/2 (or some fraction of dx), each with the same dt. 
- Do 5 or so solver iterations
- load balance
- 5 or so iterations
- Adapt (Change dt (and nt) in some regions)
- 5 or so iterations
- load balance
- 5 or so iterations 
  Rinse and repeat until convergence.

It would be very cool if we did this for many different regions in time. By this I mean solve for t in [0,T], then use our solution at time T as an initial condition to solve for t in [T,2T], and so on. We do not have time to get real adaptive in time methods working, but we can fake it based on what we choose for boundary values, or just change them randomly. 

@pranjalv123, I think we can use this with different ratios of regions/PEs and max nt/min nt to measure that.

**Comment by shigh** [comment]
I think what is in master is enough for the presentation, we can do more tomorrow if we have time.
